name: s7_service
description: A one hour exercise, based on the Darrrt project, to learn AngularDart.
dependencies:
  angular: 1.1.2
  web_components: any
  browser: any
dev_dependencies:
  unittest: any
  mock: any
transformers:
- angular:
    html_files:
      - lib/component/pirate.html
      - lib/component/badge.html
